### Admin
POST http://localhost:8080/api/member/admin
accept: */*
Content-Type: application/json

{
  "id": "asdf",
  "passWord": "asdf",
  "birthDate" : "20030903",
  "nickName": "asdf"
}


### AdminTest1
POST http://localhost:8080/adminPage/asdf
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NjIzNjA0MTR9.lUmnVjnCpAocvxxJtl89ycprPT-sP-lCbPVSD9EvSco
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NTQ0MTR9.2Qx3if4t2P0nXqo5Oixh1Wbpd-WmgAD13olwIXPWUgM
Access-Token-Expire-Time: 1662350373666
accept: */*
Content-Type: application/json

{
  "point":1000
}

### AdminTest2
POST http://localhost:8080/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NjIzNTk1NTV9.V46GiSMMSRs9xbIWEgt4O3F1mpzR4k-9mqnZw7v2RKo
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NTM1NTV9.r-v4W1LfHBqLY4Qep_ryHe1IFhKUk0uYJKN5nvt7xT8
Access-Token-Expire-Time: 1662350373666
accept: */*

### GetInfo
GET http://localhost:8080/adminPage
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NjIzNjA0MTR9.lUmnVjnCpAocvxxJtl89ycprPT-sP-lCbPVSD9EvSco
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NTQ0MTR9.2Qx3if4t2P0nXqo5Oixh1Wbpd-WmgAD13olwIXPWUgM
Access-Token-Expire-Time: 1662350373666
accept: */*