### signup
POST http://localhost:8080/api/member/signup
accept: */*
Content-Type: application/json

{
  "id": "asdf",
  "passWord": "asdf",
  "birthDate" : "20030903",
  "nickName": "asdf"
}

### signup2
POST http://localhost:8080/api/member/signup
accept: */*
Content-Type: application/json

{
  "id": "asdf2",
  "passWord": "asdf2",
  "birthDate" : "20131111",
  "nickName": "asdf2"
}

### signup3
POST http://localhost:8080/api/member/signup
accept: */*
Content-Type: application/json

{
  "id": "asdf3",
  "passWord": "asdf3",
  "birthDate" : "21131111",
  "nickName": "asdf3"
}



### duplicateCheckId
POST http://localhost:8080/api/member/chkId
accept: */*
Content-Type: application/json

{
  "id": "asdf"
}

### duplicateCheckNickname
POST http://localhost:8080/api/member/chkName
accept: */*
Content-Type: application/json

{
  "nickName": "asdf3"
}

### login
POST http://localhost:8080/api/member/login
accept: */*
Content-Type: application/json

{
  "id": "asdf",
  "passWord": "asdf"
}

### login2
POST http://localhost:8080/api/member/login
accept: */*
Content-Type: application/json

{
  "id": "asdf2",
  "passWord": "asdf2"
}

### login3
POST http://localhost:8080/api/member/login
accept: */*
Content-Type: application/json

{
  "id": "asdf311",
  "passWord": "asdf311"
}

### updateTEST
PATCH http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDQ3MzM1fQ.rG8KKPx8EBAncV-FAqLEGApgqkuDE2hUpMjbl9TJNL4
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwNDEzMzV9.5jCITMQ_ANWAQINFfSTa57CdBAfgxP9ZEC8fBLKowOw
accept: */*
Content-Type: application/json

{
  "nickName" : "변경닉네임"
}

### logout
POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDQ3MjA1fQ.ZckVFSkHgimXo9ue6yLUwi9xBCzXDXDpb0gNe1f_YFQ
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwNDEyMDV9.72lZUFmYcEGHjYt35-C_VOekNJC929jdySo0soITCIg
accept: */*

### commentPostTest
POST http://localhost:8080/api/comment?gameId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDU1NzI3fQ.jajZ9Y_WAfKJT8dUl2P1_grSwJOhfCns7KsxWoZ48vE
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwNDk3Mjd9.JYFKhKtYr7PFfpatJeAqUUub5mSjjkcZrfc6JH8h1Dc
accept: */*
Content-Type: application/json

{
  "content" : "1?"
}

### commentGetTest
GET http://localhost:8080/api/comment?gameId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDQxNTU1fQ._zDHf5qcBV5emIzB8IiVHZ8Bm3yfQmhZ811TvBcHfyI
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwMzU1NTV9.-lSsvrpGy2fhpOtyS2lgLbj4tVZzIBC0r4OlFBuhKyg
accept: */*


### commentPatchTest
PATCH http://localhost:8080/api/comment?gameId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDQxNTU1fQ._zDHf5qcBV5emIzB8IiVHZ8Bm3yfQmhZ811TvBcHfyI
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwMzU1NTV9.-lSsvrpGy2fhpOtyS2lgLbj4tVZzIBC0r4OlFBuhKyg
accept: */*
Content-Type: application/json

{
  "content" : "내용입니다2."
}

### commentDeleteTest
DELETE http://localhost:8080/api/comment?id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDQxNTU1fQ._zDHf5qcBV5emIzB8IiVHZ8Bm3yfQmhZ811TvBcHfyI
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwMzU1NTV9.-lSsvrpGy2fhpOtyS2lgLbj4tVZzIBC0r4OlFBuhKyg
accept: */*


### myPageTest
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMzUyMzAwfQ.-FZygZef-NfKFnET6XVwA66rhr9RgwgXzr4TaHAMX7Y
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NDYzMDB9.PwU7eVzXEvnzCcxk4iQ53DR6F4lXuIELSzIAaQ3MfcE
accept: */*


### totalTest
GET http://localhost:8080/api/ranking
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMzUyMzAwfQ.-FZygZef-NfKFnET6XVwA66rhr9RgwgXzr4TaHAMX7Y
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NDYzMDB9.PwU7eVzXEvnzCcxk4iQ53DR6F4lXuIELSzIAaQ3MfcE
accept: */*

### gameRankTest
GET http://localhost:8080/api/ranking/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMzUyNTIyfQ.OU8cL_xqFQEvj7FHcDzByUp7JH2yhLOJeSeiL9Uz3zE
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI5NDY1MjJ9.OzOAyfF96l1SirtorevRQgVMTz2i4ozV4-m7TR8q040
accept: */*

### WithdrawalTest
DELETE http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyNDU1NjM0fQ.rsf96HjmhbperpDkOLKoqlPw_ICkC19bc-oxoaC4824
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjMwNDk2MzR9.visbqnXjT4Q1FH7E4vbdKH-gauX25lIMwUTyW0yaX8g
accept: */*

###Test
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjA4MjE2fQ.d1C_dCmJIBOEO2J2rczwpH4crVusCNWX3CJA28U1nFQ
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4MDIyMTZ9.3rj1LH-dIpxqo-4Jt8-1MAh8AUwE3b_QWHhCsdu-_T0
accept: */*
Content-Type: application/json