### signup
POST http://localhost:8080/api/member/signup
accept: */*
Content-Type: application/json

{
  "id": "asdf",
  "passWord": "asdf",
  "birthDate" : "20030903",
  "nickName": "asdf"
}

### signup2
POST http://localhost:8080/api/member/signup
accept: */*
Content-Type: application/json

{
  "id": "asdf2",
  "passWord": "asdf2",
  "birthDate" : "20131111",
  "nickName": "asdf2"
}


### duplicateCheckId
POST http://localhost:8080/api/member/chkId
accept: */*
Content-Type: application/json

{
  "id": "asdf"
}

### duplicateCheckNickname
POST http://localhost:8080/api/member/chkName
accept: */*
Content-Type: application/json

{
  "nickName": "asSdf"
}

### login
POST http://localhost:8080/api/member/login
accept: */*
Content-Type: application/json

{
  "id": "asdf",
  "passWord": "asdf"
}

### login2
POST http://localhost:8080/api/member/login
accept: */*
Content-Type: application/json

{
  "id": "asdf2",
  "passWord": "asdf2"
}

### oddtest
POST http://localhost:8080/api/game/oddeven
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjkxMjExfQ.hTIwqRbmXc4GTW5cxzbFJHnmIefj12uD44zc9qh49xk
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4ODUyMTF9.Na1ewqCCdcvzFm6V2sLOtAa6vWi1JV55nt9bJqKaNEE
accept: */*
Content-Type: application/json

{
  "point" : 10,
  "number" : 1
}

### dicetest
POST http://localhost:8080/api/game/dice
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjg3NDUwfQ.Bwce5yvxZz6qu5P65cQo5M6p1KKgTSk9611JHwUK5-8
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4ODE0NTB9.dx2LhMNdswvKlTw6njZTGNuGtjobLdByQ9PGZ21-oT0
accept: */*
Content-Type: application/json

{
  "point" : 5,
  "number" : 5
}

### commentPostTest
POST http://localhost:8080/api/comment?gameId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjkxMjExfQ.hTIwqRbmXc4GTW5cxzbFJHnmIefj12uD44zc9qh49xk
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4ODUyMTF9.Na1ewqCCdcvzFm6V2sLOtAa6vWi1JV55nt9bJqKaNEE
accept: */*
Content-Type: application/json

{
  "content" : "내용입니다."
}

### commentGetTest
GET http://localhost:8080/api/comment?gameId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjkxMjExfQ.hTIwqRbmXc4GTW5cxzbFJHnmIefj12uD44zc9qh49xk
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4ODUyMTF9.Na1ewqCCdcvzFm6V2sLOtAa6vWi1JV55nt9bJqKaNEE
accept: */*


### commentPatchTest
PATCH http://localhost:8080/api/comment?gameId=1&id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjA3MzQ3fQ.JdUqNwcRXoUxojA-zufoH_W4Zragl5Gi2Uv5dWpO_Ug
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4MDEzNDd9.Z2W9UCQsZAALGUZVAamA94-10OCgLzMEjd-Dwsk0CdM
accept: */*
Content-Type: application/json

{
  "content" : "내용입니다2."
}

### commentDeleteTest
DELETE http://localhost:8080/api/comment?gameId=1&id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjA3MzQ3fQ.JdUqNwcRXoUxojA-zufoH_W4Zragl5Gi2Uv5dWpO_Ug
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4MDEzNDd9.Z2W9UCQsZAALGUZVAamA94-10OCgLzMEjd-Dwsk0CdM
accept: */*


### myPageTest
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmMiIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjIwODMyOH0.dDQRX5zTMFReyYrA4GshPXz2InptioT1PkWEQ6BIYtI
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4MDIzMjh9.3U21jJR9ojiPlOQK2Ey5Wm62sqgLAyRc2-odX5jZNd0
accept: */*


###Test
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYyMjA4MjE2fQ.d1C_dCmJIBOEO2J2rczwpH4crVusCNWX3CJA28U1nFQ
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI4MDIyMTZ9.3rj1LH-dIpxqo-4Jt8-1MAh8AUwE3b_QWHhCsdu-_T0
accept: */*
Content-Type: application/json